name: CWL Workflow

on:
  push:
    branches: [ main ]

jobs:
  run-cwl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install cwlref-runner

    - name: Set execute permission for run_workflow.py
      run: chmod +x run_workflow.py

    - name: Run CWL workflow
      run: |
        cwltool run_workflow.cwl input.yml

